# 非 host 版本, 不使用本机代理
version: '3.3'
services:
#  mongo:
#    image: mongo:5.0.18
#    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
#    container_name: mongo
#    restart: always
#    ports:
#      # 生产环境建议不要暴露
#      - 27017:27017
#    environment:
#      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
#      - MONGO_INITDB_ROOT_USERNAME=username
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    volumes:
#      - ./mongo/data:/data/db
  pg:
    image: ankane/pgvector
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 5433:5432
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=chubby
      - POSTGRES_PASSWORD=990721
      - POSTGRES_DB=bizgpt
    volumes:
      - ./pg/data:/var/lib/postgresql/data
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql

  # mongo2:
  #   image: mongo:5.0.18
  #   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
  #   container_name: mongo2
  #   restart: always
  #   ports:
  #     # 生产环境建议不要暴露
  #     - 27018:27018
  #   environment:
  #     # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
  #     - MONGO_INITDB_ROOT_USERNAME=username
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #   volumes:
  #     - ./mongo/data:/data/db


  # mongo3:
  #   image: mongo:5.0.18
  #   # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
  #   container_name: mongo3
  #   restart: always
  #   ports:
  #     # 生产环境建议不要暴露
  #     - 27019:27019
  #   environment:
  #     # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
  #     - MONGO_INITDB_ROOT_USERNAME=username
  #     - MONGO_INITDB_ROOT_PASSWORD=password


  #   volumes:
  #     - ./mongo/data:/data/db
